"""Utilities for counting small two-terminal RLC one-port topologies."""

from .core import (
    COUNT_PROFILES,
    LOCAL_SP_RELATION,
    SIMPLE_PRIMITIVE_BUNDLES,
    AssignedSupportCensusResult,
    AssignedSupportFact,
    AssignedSupportRecord,
    AssignmentCensusResult,
    AssignmentFact,
    AssignmentRecord,
    BundleSet,
    BundleSetCensusResult,
    BundleSetRecord,
    BundleTypeRecord,
    ComponentConstraints,
    CountQuery,
    IntegerRange,
    NetworkCensusResult,
    NetworkFact,
    NetworkRecord,
    NetworkRelation,
    ReducedFactor,
    ReducedSignature,
    ReductionCensusResult,
    SimplePrimitiveBundle,
    SupportCensusResult,
    SupportRecord,
    assigned_support_census,
    assignment_census,
    bundle_set_census,
    canonical_reduced_signature,
    enum_assigned_supports,
    enum_assignments,
    enum_bundle_sets,
    enum_bundle_types,
    enum_networks,
    enum_supports,
    factor_from_simple_primitive_bundle,
    iter_bundle_sets,
    network_census,
    normalise_parallel_factor,
    normalise_reduced_factor,
    normalise_series_factor,
    primitive_factor,
    reduced_signature_component_counts,
    reduction_census,
    support_census,
    validate_network_relation,
)

__all__ = [
    # Query/configuration types and constants.
    "IntegerRange",
    "CountQuery",
    "ComponentConstraints",
    "COUNT_PROFILES",
    "SIMPLE_PRIMITIVE_BUNDLES",
    "SimplePrimitiveBundle",
    # Count functions and results.
    "SupportCensusResult",
    "BundleSetCensusResult",
    "AssignmentFact",
    "AssignmentCensusResult",
    "AssignedSupportFact",
    "AssignedSupportCensusResult",
    "NetworkFact",
    "NetworkCensusResult",
    "ReductionCensusResult",
    "support_census",
    "bundle_set_census",
    "assignment_census",
    "assigned_support_census",
    "network_census",
    "reduction_census",
    # Enumeration record types and functions.
    "SupportRecord",
    "BundleTypeRecord",
    "BundleSetRecord",
    "AssignmentRecord",
    "AssignedSupportRecord",
    "NetworkRecord",
    "enum_supports",
    "enum_bundle_types",
    "enum_bundle_sets",
    "enum_assignments",
    "enum_assigned_supports",
    "enum_networks",
    # Reduction helpers and fact types.
    "BundleSet",
    "ReducedFactor",
    "ReducedSignature",
    "canonical_reduced_signature",
    "factor_from_simple_primitive_bundle",
    "normalise_parallel_factor",
    "normalise_reduced_factor",
    "normalise_series_factor",
    "primitive_factor",
    "reduced_signature_component_counts",
    "iter_bundle_sets",
    # Relations.
    "NetworkRelation",
    "LOCAL_SP_RELATION",
    "validate_network_relation",
]
